import React,{useEffect,useState} from 'react'
import {Check,Flag,Plus,Trash2,Edit3,Save} from 'lucide-react'
import DiaryPaper from '../components/DiaryPaper'
import Modal from '../components/Modal'
import Toast from '../components/Toast'
import {api,request} from '../lib/api'
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
export default function Daily(){
 const [data,setData]=useState({schedule:[],tasks:[],goals:[]}),[open,setOpen]=useState(null),[editing,setEditing]=useState(null),[form,setForm]=useState({}),[toast,setToast]=useState('')
 const load=()=>request(api.get('/diary/daily',{params:{date:today()}})).then(setData).catch(e=>setToast(e.message));useEffect(()=>{load()},[])
 const save=async(type)=>{try{const url=type==='schedule'?'schedules':type==='tasks'?'tasks':'goals';if(editing)await request(api.patch(`/diary/${url}/${editing.id}`,form));else await request(api.post(`/diary/${type}`,{...form,date:today()}));setOpen(null);setEditing(null);setForm({});setToast(editing?'Entry updated':'Saved to today’s page');load()}catch(e){setToast(e.message)}}
 const del=async(type,id)=>{if(!confirm('Delete this entry?'))return;const url=type==='schedule'?'schedules':type==='tasks'?'tasks':'goals';try{await request(api.delete(`/diary/${url}/${id}`));setToast('Entry deleted');load()}catch(e){setToast(e.message)}}
 const edit=(type,item)=>{setEditing(item);setOpen(type);setForm({...item,progress:item.progress??0})}
 const toggle=async(t)=>{await request(api.patch(`/diary/tasks/${t.id}`,{completed:!t.completed}));load()}
 const add=(type)=>{setEditing(null);setOpen(type);setForm(type==='schedule'?{time:'09:00',activity:'',subject:'',notes:''}:type==='tasks'?{name:'',description:'',priority:'normal',due_time:''}:{goal:'',target:'',progress:0,status:'in-progress'})}
 const completed=data.tasks.filter(x=>x.completed).length
 return <DiaryPaper title="Today, on paper" page="01"><div className="paper-grid">
  <Section title="TODAY’S SCHEDULE" sub="How the day should feel" onAdd={()=>add('schedule')}><div className="schedule-list">{data.schedule.length?data.schedule.map(s=><div className="schedule-row" key={s.id}><time>{s.time}</time><div><strong>{s.activity}</strong><small>{s.subject}{s.notes?` • ${s.notes}`:''}</small></div><Actions onEdit={()=>edit('schedule',s)} onDelete={()=>del('schedule',s.id)}/></div>):<Empty text="Your schedule is blank. Give the day a shape."/>}</div></Section>
  <Section title="DAILY TASKS" sub="Small wins, stacked" onAdd={()=>add('tasks')} ruled><div className="task-list">{data.tasks.length?data.tasks.map(t=><div className={`task-row ${t.completed?'done':''}`} key={t.id}><button className="check" onClick={()=>toggle(t)}>{t.completed&&<Check size={15}/>}</button><div><strong>{t.name}</strong><small>{t.description||'No description'} {t.due_time&&`• ${t.due_time}`}</small></div><span className={`priority ${t.priority}`}>{t.priority}</span><Actions onEdit={()=>edit('tasks',t)} onDelete={()=>del('tasks',t.id)}/></div>):<Empty text="No tasks for today. Add your first one."/>}</div><div className="progress-line"><span style={{width:`${data.tasks.length?completed/data.tasks.length*100:0}%`}}/></div><small className="muted">{completed}/{data.tasks.length} tasks complete</small></Section>
  <Section title="TODAY’S GOALS" sub="Move the needle" onAdd={()=>add('goals')} full><div className="goal-grid">{data.goals.length?data.goals.map(g=><div className="goal-card" key={g.id}><Flag size={17}/><div><strong>{g.goal}</strong><small>Target: {g.target||'No target'}</small><div className="progress-line"><span style={{width:`${g.progress}%`}}/></div></div><b>{g.progress}%</b><Actions onEdit={()=>edit('goals',g)} onDelete={()=>del('goals',g.id)}/></div>):<Empty text="No goals written yet. Make one measurable."/>}</div></Section>
 </div><Modal open={!!open} onClose={()=>{setOpen(null);setEditing(null)}} title={`${editing?'Edit':'Add'} ${open||''}`}><EntryForm type={open} form={form} setForm={setForm} save={save} editing={!!editing}/></Modal><Toast message={toast} onDone={()=>setToast('')}/></DiaryPaper>
}
function Section({title,sub,onAdd,children,ruled,full}){return <div className={`paper-col ${ruled?'ruled ':''}${full?'full':''}`}><div className="section-head"><div><span className="eyebrow">{title}</span><h2>{sub}</h2></div><button className="small-btn" onClick={onAdd}><Plus size={15}/> Add</button></div>{children}</div>}
function Actions({onEdit,onDelete}){return <div className="entry-actions"><button className="icon-btn" title="Edit" onClick={onEdit}><Edit3 size={14}/></button><button className="icon-btn danger-icon" title="Delete" onClick={onDelete}><Trash2 size={14}/></button></div>}
function Empty({text}){return <div className="empty"><span>✦</span>{text}</div>}
function EntryForm({type,form,setForm,save,editing}){const f=(k)=><input value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})}/>;return <div className="form-stack">{type==='schedule'&&<><label>Time{f('time')}</label><label>Activity{f('activity')}</label><label>Subject{f('subject')}</label><label>Notes{f('notes')}</label></>}{type==='tasks'&&<><label>Task name{f('name')}</label><label>Description{f('description')}</label><label>Priority<select value={form.priority||'normal'} onChange={e=>setForm({...form,priority:e.target.value})}><option>low</option><option>normal</option><option>high</option></select></label><label>Due time{f('due_time')}</label></>}{type==='goals'&&<><label>Goal{f('goal')}</label><label>Target{f('target')}</label><label>Progress (%)<input type="number" min="0" max="100" value={form.progress??0} onChange={e=>setForm({...form,progress:e.target.value})}/></label><label>Status<select value={form.status||'in-progress'} onChange={e=>setForm({...form,status:e.target.value})}><option value="in-progress">In progress</option><option value="completed">Completed</option><option value="declined">Declined</option></select></label></>}<button className="primary wide" onClick={()=>save(type)}><Save size={15}/>{editing?'Update entry':'Save entry'}</button></div>}
