import express from 'express'
import cors from 'cors'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import Database from 'better-sqlite3'
import { createServer } from 'http'
import { Server } from 'socket.io'
import path from 'path'
import { fileURLToPath } from 'url'
import fs from 'fs'

const __dirname=path.dirname(fileURLToPath(import.meta.url))
fs.mkdirSync(path.join(__dirname,'data'),{recursive:true})
const db=new Database(path.join(__dirname,'data/diary.sqlite'))
db.pragma('journal_mode = WAL')
db.exec(`
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS schedules(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,date TEXT,time TEXT,activity TEXT,subject TEXT,notes TEXT,completed INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,date TEXT,name TEXT,description TEXT,priority TEXT DEFAULT 'normal',due_time TEXT,completed INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS goals(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,date TEXT,goal TEXT,target TEXT,status TEXT DEFAULT 'in-progress',progress INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS study_sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,date TEXT,start_time TEXT,end_time TEXT,duration INTEGER,type TEXT);
CREATE TABLE IF NOT EXISTS rooms(id INTEGER PRIMARY KEY AUTOINCREMENT,creator_id INTEGER,name TEXT,description TEXT,max_members INTEGER,subject TEXT,type TEXT DEFAULT 'public',password_hash TEXT,status TEXT DEFAULT 'Studying',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS room_members(room_id INTEGER,user_id INTEGER,joined_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(room_id,user_id));
CREATE TABLE IF NOT EXISTS room_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,room_id INTEGER,user_id INTEGER,message TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS study_live_sessions(user_id INTEGER PRIMARY KEY,room_id INTEGER,started_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS weekly_plans(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,week_start TEXT NOT NULL,date TEXT NOT NULL,content TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS weekly_chapters(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,week_start TEXT NOT NULL,name TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
`)
const app=express(),server=createServer(app),io=new Server(server,{cors:{origin:true,credentials:true}})
app.use(cors());app.use(express.json())
const JWT_SECRET=process.env.JWT_SECRET||'change-this-in-production'
function token(user){return jwt.sign({id:user.id},JWT_SECRET,{expiresIn:'30d'})}
function auth(req,res,next){try{const p=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),JWT_SECRET);req.user=db.prepare('SELECT id,name,email FROM users WHERE id=?').get(p.id);if(!req.user)throw Error();next()}catch{res.status(401).json({error:'Please sign in again.'})}}
function day(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),x=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${x}`}
function mondayOf(d=new Date()){const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
function validDate(v){return /^\d{4}-\d{2}-\d{2}$/.test(String(v||''))}

app.post('/api/auth/register',async(req,res)=>{try{const {name,email,password}=req.body;if(!name||!email||!password||password.length<6)return res.status(400).json({error:'Name, email and a 6+ character password are required.'});const hash=await bcrypt.hash(password,12);const info=db.prepare('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)').run(name,email.toLowerCase(),hash);const user={id:info.lastInsertRowid,name,email:email.toLowerCase()};res.json({token:token(user),user})}catch(e){res.status(400).json({error:e.code==='SQLITE_CONSTRAINT_UNIQUE'?'An account with this email already exists.':'Could not create account.'})}})
app.post('/api/auth/login',async(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE email=?').get(String(req.body.email||'').toLowerCase());if(!u||!(await bcrypt.compare(req.body.password||'',u.password_hash)))return res.status(401).json({error:'Email or password is incorrect.'});const user={id:u.id,name:u.name,email:u.email};res.json({token:token(user),user})})
app.get('/api/auth/me',auth,(req,res)=>res.json({user:req.user}))

app.get('/api/diary/daily',auth,(req,res)=>{const date=validDate(req.query.date)?req.query.date:day();res.json({date,schedule:db.prepare('SELECT * FROM schedules WHERE user_id=? AND date=? ORDER BY time,id').all(req.user.id,date),tasks:db.prepare('SELECT * FROM tasks WHERE user_id=? AND date=? ORDER BY completed,id DESC').all(req.user.id,date).map(x=>({...x,completed:!!x.completed})),goals:db.prepare('SELECT * FROM goals WHERE user_id=? AND date=? ORDER BY id DESC').all(req.user.id,date)})})
app.post('/api/diary/schedule',auth,(req,res)=>{const {date,time,activity,subject,notes}=req.body;if(!validDate(date)||!activity)return res.status(400).json({error:'Date and activity are required.'});const r=db.prepare('INSERT INTO schedules(user_id,date,time,activity,subject,notes) VALUES(?,?,?,?,?,?)').run(req.user.id,date,time||'',activity,subject||'',notes||'');res.json({id:r.lastInsertRowid})})
app.patch('/api/diary/schedules/:id',auth,(req,res)=>{const {time,activity,subject,notes}=req.body;db.prepare('UPDATE schedules SET time=?,activity=?,subject=?,notes=? WHERE id=? AND user_id=?').run(time||'',activity||'',subject||'',notes||'',req.params.id,req.user.id);res.json({ok:true})})
app.delete('/api/diary/schedules/:id',auth,(req,res)=>{db.prepare('DELETE FROM schedules WHERE id=? AND user_id=?').run(req.params.id,req.user.id);res.json({ok:true})})
app.post('/api/diary/tasks',auth,(req,res)=>{const {date,name,description,priority,due_time}=req.body;if(!validDate(date)||!name)return res.status(400).json({error:'Date and task name are required.'});const r=db.prepare('INSERT INTO tasks(user_id,date,name,description,priority,due_time) VALUES(?,?,?,?,?,?)').run(req.user.id,date,name,description||'',priority||'normal',due_time||'');res.json({id:r.lastInsertRowid})})
app.patch('/api/diary/tasks/:id',auth,(req,res)=>{const old=db.prepare('SELECT * FROM tasks WHERE id=? AND user_id=?').get(req.params.id,req.user.id);if(!old)return res.status(404).json({error:'Task not found.'});const body=req.body;db.prepare('UPDATE tasks SET name=?,description=?,priority=?,due_time=?,completed=? WHERE id=? AND user_id=?').run(body.name??old.name,body.description??old.description,body.priority??old.priority,body.due_time??old.due_time,body.completed===undefined?old.completed:(body.completed?1:0),req.params.id,req.user.id);res.json({ok:true})})
app.delete('/api/diary/tasks/:id',auth,(req,res)=>{db.prepare('DELETE FROM tasks WHERE id=? AND user_id=?').run(req.params.id,req.user.id);res.json({ok:true})})
app.post('/api/diary/goals',auth,(req,res)=>{const {date,goal,target,progress,status}=req.body;if(!validDate(date)||!goal)return res.status(400).json({error:'Date and goal are required.'});const r=db.prepare('INSERT INTO goals(user_id,date,goal,target,progress,status) VALUES(?,?,?,?,?,?)').run(req.user.id,date,goal,target||'',Math.max(0,Math.min(100,Number(progress)||0)),status||'in-progress');res.json({id:r.lastInsertRowid})})
app.patch('/api/diary/goals/:id',auth,(req,res)=>{const old=db.prepare('SELECT * FROM goals WHERE id=? AND user_id=?').get(req.params.id,req.user.id);if(!old)return res.status(404).json({error:'Goal not found.'});db.prepare('UPDATE goals SET goal=?,target=?,progress=?,status=? WHERE id=? AND user_id=?').run(req.body.goal??old.goal,req.body.target??old.target,Math.max(0,Math.min(100,Number(req.body.progress??old.progress))),req.body.status??old.status,req.params.id,req.user.id);res.json({ok:true})})
app.delete('/api/diary/goals/:id',auth,(req,res)=>{db.prepare('DELETE FROM goals WHERE id=? AND user_id=?').run(req.params.id,req.user.id);res.json({ok:true})})

app.get('/api/diary/weekly',auth,(req,res)=>{const base=validDate(req.query.weekStart)?new Date(`${req.query.weekStart}T12:00:00`):mondayOf();const monday=mondayOf(base),weekStart=day(monday),days=[];for(let i=0;i<7;i++){const d=new Date(monday);d.setDate(monday.getDate()+i);const ds=day(d);const c=db.prepare('SELECT COUNT(*) c FROM tasks WHERE user_id=? AND date=? AND completed=1').get(req.user.id,ds).c;const g=db.prepare('SELECT COUNT(*) c FROM goals WHERE user_id=? AND date=?').get(req.user.id,ds).c;const sec=db.prepare('SELECT COALESCE(SUM(duration),0) s FROM study_sessions WHERE user_id=? AND date=?').get(req.user.id,ds).s;const plans=db.prepare('SELECT * FROM weekly_plans WHERE user_id=? AND week_start=? AND date=? ORDER BY id').all(req.user.id,weekStart,ds);days.push({date:ds,day:d.toLocaleDateString(undefined,{weekday:'long'}),completed:c,goals:g,seconds:sec,minutes:sec/60,plans})}const chapters=db.prepare('SELECT * FROM weekly_chapters WHERE user_id=? AND week_start=? ORDER BY id').all(req.user.id,weekStart);res.json({weekStart,days,chapters})})
app.post('/api/diary/weekly/plans',auth,(req,res)=>{const {weekStart,date,content}=req.body;if(!validDate(weekStart)||!validDate(date)||!content?.trim())return res.status(400).json({error:'Week, date and plan are required.'});const r=db.prepare('INSERT INTO weekly_plans(user_id,week_start,date,content) VALUES(?,?,?,?)').run(req.user.id,weekStart,date,content.trim());res.json({id:r.lastInsertRowid})})
app.patch('/api/diary/weekly/plans/:id',auth,(req,res)=>{db.prepare('UPDATE weekly_plans SET content=? WHERE id=? AND user_id=?').run(String(req.body.content||'').trim(),req.params.id,req.user.id);res.json({ok:true})})
app.delete('/api/diary/weekly/plans/:id',auth,(req,res)=>{db.prepare('DELETE FROM weekly_plans WHERE id=? AND user_id=?').run(req.params.id,req.user.id);res.json({ok:true})})
app.post('/api/diary/weekly/chapters',auth,(req,res)=>{const {weekStart,name}=req.body;if(!validDate(weekStart)||!name?.trim())return res.status(400).json({error:'Week and chapter name are required.'});const r=db.prepare('INSERT INTO weekly_chapters(user_id,week_start,name) VALUES(?,?,?)').run(req.user.id,weekStart,name.trim());res.json({id:r.lastInsertRowid})})
app.patch('/api/diary/weekly/chapters/:id',auth,(req,res)=>{db.prepare('UPDATE weekly_chapters SET name=? WHERE id=? AND user_id=?').run(String(req.body.name||'').trim(),req.params.id,req.user.id);res.json({ok:true})})
app.delete('/api/diary/weekly/chapters/:id',auth,(req,res)=>{db.prepare('DELETE FROM weekly_chapters WHERE id=? AND user_id=?').run(req.params.id,req.user.id);res.json({ok:true})})

app.get('/api/diary/monthly',auth,(req,res)=>{const y=Number(req.query.year),m=Number(req.query.month);if(!y||m<1||m>12)return res.status(400).json({error:'Invalid month.'});const prefix=`${y}-${String(m).padStart(2,'0')}`;const tasks=db.prepare("SELECT COUNT(*) total,SUM(completed) completed FROM tasks WHERE user_id=? AND date LIKE ?").get(req.user.id,prefix+'-%');const sec=db.prepare("SELECT COALESCE(SUM(duration),0) s FROM study_sessions WHERE user_id=? AND date LIKE ?").get(req.user.id,prefix+'-%').s;const rows=db.prepare("SELECT CAST(strftime('%d',date) AS INTEGER) day,COUNT(*) tasks,SUM(completed) completed FROM tasks WHERE user_id=? AND date LIKE ? GROUP BY date").all(req.user.id,prefix+'-%');const days={};rows.forEach(r=>days[r.day]={tasks:r.tasks,completed:r.completed||0,minutes:0,seconds:0});const ss=db.prepare("SELECT CAST(strftime('%d',date) AS INTEGER) day,SUM(duration) seconds FROM study_sessions WHERE user_id=? AND date LIKE ? GROUP BY date").all(req.user.id,prefix+'-%');ss.forEach(r=>{days[r.day]??={tasks:0,completed:0,minutes:0,seconds:0};days[r.day].seconds=r.seconds;days[r.day].minutes=r.seconds/60});res.json({totalTasks:tasks.total||0,completedTasks:tasks.completed||0,totalMinutes:sec/60,totalSeconds:sec,goalRate:tasks.total?Math.round((tasks.completed||0)/tasks.total*100):0,days})})

app.post('/api/study/sessions',auth,(req,res)=>{const duration=Math.max(0,Math.floor(Number(req.body.duration)||0)),now=new Date(),start=new Date(now.getTime()-duration*1000);if(duration<1)return res.status(400).json({error:'Study at least one second before saving a session.'});db.prepare('INSERT INTO study_sessions(user_id,date,start_time,end_time,duration,type) VALUES(?,?,?,?,?,?)').run(req.user.id,day(now),start.toISOString(),now.toISOString(),duration,req.body.type||'SELF STUDY');res.json({ok:true,duration})})
app.post('/api/study/group/start',auth,(req,res)=>{const room=db.prepare('SELECT * FROM rooms WHERE id=?').get(Number(req.body.roomId));if(!room||room.status==='Ended')return res.status(404).json({error:'Study room not found.'});const member=db.prepare('SELECT 1 FROM room_members WHERE room_id=? AND user_id=?').get(room.id,req.user.id);if(!member)return res.status(403).json({error:'Join this room first.'});const now=new Date().toISOString();db.prepare('INSERT INTO study_live_sessions(user_id,room_id,started_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET room_id=excluded.room_id,started_at=excluded.started_at,updated_at=excluded.updated_at').run(req.user.id,room.id,now,now);res.json({ok:true,startedAt:now})})
app.post('/api/study/group/heartbeat',auth,(req,res)=>{const live=db.prepare('SELECT * FROM study_live_sessions WHERE user_id=?').get(req.user.id);if(!live)return res.json({ok:true,active:false});db.prepare('UPDATE study_live_sessions SET updated_at=? WHERE user_id=?').run(new Date().toISOString(),req.user.id);res.json({ok:true,active:true,roomId:live.room_id})})
app.post('/api/study/group/stop',auth,(req,res)=>{const live=db.prepare('SELECT * FROM study_live_sessions WHERE user_id=?').get(req.user.id);if(!live)return res.json({ok:true,duration:0});const started=new Date(live.started_at),now=new Date(),duration=Math.max(0,Math.floor((now-started)/1000));if(duration>0)db.prepare('INSERT INTO study_sessions(user_id,date,start_time,end_time,duration,type) VALUES(?,?,?,?,?,?)').run(req.user.id,day(now),started.toISOString(),now.toISOString(),duration,'GROUP STUDY');db.prepare('DELETE FROM study_live_sessions WHERE user_id=?').run(req.user.id);res.json({ok:true,duration})})
app.get('/api/study/live',auth,(req,res)=>{const live=db.prepare('SELECT l.*,r.name room_name,r.type room_type FROM study_live_sessions l JOIN rooms r ON r.id=l.room_id WHERE l.user_id=?').get(req.user.id);if(!live)return res.json({active:false,seconds:0});const seconds=Math.max(0,Math.floor((Date.now()-new Date(live.started_at).getTime())/1000));res.json({active:true,seconds,roomId:live.room_id,roomName:live.room_name,roomType:live.room_type})})

app.get('/api/dashboard',auth,(req,res)=>{const sessions=db.prepare('SELECT type,COALESCE(SUM(duration),0) seconds FROM study_sessions WHERE user_id=? GROUP BY type').all(req.user.id);const selfSeconds=sessions.find(x=>x.type==='SELF STUDY')?.seconds||0,groupSeconds=sessions.find(x=>x.type==='GROUP STUDY')?.seconds||0;const live=db.prepare('SELECT l.*,r.name room_name FROM study_live_sessions l JOIN rooms r ON r.id=l.room_id WHERE l.user_id=?').get(req.user.id);const liveSeconds=live?Math.max(0,Math.floor((Date.now()-new Date(live.started_at).getTime())/1000)):0;const tc=db.prepare('SELECT COUNT(*) total,SUM(completed) done FROM tasks WHERE user_id=?').get(req.user.id);const gc=db.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END) done FROM goals WHERE user_id=?").get(req.user.id);const week=[];const now=new Date();for(let i=6;i>=0;i--){const d=new Date(now);d.setDate(now.getDate()-i);const ds=day(d);const s=db.prepare('SELECT COALESCE(SUM(duration),0) seconds FROM study_sessions WHERE user_id=? AND date=?').get(req.user.id,ds).seconds;week.push({day:d.toLocaleDateString(undefined,{weekday:'short'}),minutes:s/60,seconds:s})}const studiedDays=db.prepare('SELECT DISTINCT date FROM study_sessions WHERE user_id=? ORDER BY date DESC').all(req.user.id).map(x=>x.date);let streak=0;for(let i=0;i<studiedDays.length;i++){const d=new Date();d.setDate(d.getDate()-i);if(studiedDays.includes(day(d)))streak++;else break}const totalSeconds=selfSeconds+groupSeconds+liveSeconds,completion=tc.total?tc.done/tc.total:0,goal=gc.total?gc.done/gc.total:0,score=Math.round((completion*.4+goal*.25+Math.min(totalSeconds/3600/20,1)*.25+Math.min(streak/7,1)*.1)*100);res.json({totalMinutes:totalSeconds/60,selfMinutes:selfSeconds/60,groupMinutes:(groupSeconds+liveSeconds)/60,totalSeconds,selfSeconds,groupSeconds,liveGroupSeconds:liveSeconds,liveGroupRoomId:live?.room_id||null,liveGroupRoomName:live?.room_name||null,tasksCompleted:tc.done||0,tasksRemaining:(tc.total||0)-(tc.done||0),goalsCompleted:gc.done||0,score,streak,week})})

app.get('/api/rooms',auth,(req,res)=>{const rooms=db.prepare(`SELECT r.id,r.creator_id,r.name,r.description,r.max_members,r.subject,r.type,r.status,r.created_at,u.name creator,(SELECT COUNT(*) FROM room_members rm WHERE rm.room_id=r.id) participants,EXISTS(SELECT 1 FROM room_members me WHERE me.room_id=r.id AND me.user_id=?) joined FROM rooms r JOIN users u ON u.id=r.creator_id WHERE r.status!='Ended' ORDER BY r.id DESC`).all(req.user.id).map(r=>({...r,joined:!!r.joined}));res.json(rooms)})
app.post('/api/rooms',auth,async(req,res)=>{const {name,description,maxMembers,subject,type,password}=req.body;if(!name)return res.status(400).json({error:'Room name is required.'});if(type==='private'&&!password)return res.status(400).json({error:'Private rooms need a password.'});const hash=type==='private'?await bcrypt.hash(String(password),12):null;const r=db.prepare('INSERT INTO rooms(creator_id,name,description,max_members,subject,type,password_hash) VALUES(?,?,?,?,?,?,?)').run(req.user.id,name,description||'',Math.max(2,Math.min(50,Number(maxMembers)||10)),subject||'',type==='private'?'private':'public',hash);db.prepare('INSERT INTO room_members(room_id,user_id) VALUES(?,?)').run(r.lastInsertRowid,req.user.id);const room=db.prepare(`SELECT r.*,u.name creator,(SELECT COUNT(*) FROM room_members rm WHERE rm.room_id=r.id) participants FROM rooms r JOIN users u ON u.id=r.creator_id WHERE r.id=?`).get(r.lastInsertRowid);res.json({room})})
app.post('/api/rooms/:id/join',auth,async(req,res)=>{const room=db.prepare('SELECT * FROM rooms WHERE id=?').get(req.params.id);if(!room||room.status==='Ended')return res.status(404).json({error:'Study room not found.'});const already=db.prepare('SELECT 1 FROM room_members WHERE room_id=? AND user_id=?').get(room.id,req.user.id);if(already)return res.json({ok:true,room});const count=db.prepare('SELECT COUNT(*) c FROM room_members WHERE room_id=?').get(room.id).c;if(count>=room.max_members)return res.status(409).json({error:'This study room is full.'});if(room.type==='private'){const password=String(req.body.password||'');if(!password||!room.password_hash)return res.status(401).json({error:'Enter the private room password.'});if(!(await bcrypt.compare(password,room.password_hash)))return res.status(401).json({error:'Incorrect room password.'})}db.prepare('INSERT INTO room_members(room_id,user_id) VALUES(?,?)').run(room.id,req.user.id);res.json({ok:true,room})})
app.get('/api/rooms/:id',auth,(req,res)=>{const room=db.prepare(`SELECT r.id,r.creator_id,r.name,r.description,r.max_members,r.subject,r.type,r.status,u.name creator,(SELECT COUNT(*) FROM room_members rm WHERE rm.room_id=r.id) participants FROM rooms r JOIN users u ON u.id=r.creator_id WHERE r.id=?`).get(req.params.id);if(!room||room.status==='Ended')return res.status(404).json({error:'Study room not found.'});const member=db.prepare('SELECT 1 FROM room_members WHERE room_id=? AND user_id=?').get(room.id,req.user.id);if(!member)return res.status(403).json({error:'Join this room before opening it.'});const participants=db.prepare('SELECT u.id,u.name FROM room_members rm JOIN users u ON u.id=rm.user_id WHERE rm.room_id=? ORDER BY rm.joined_at').all(room.id);res.json({...room,participantsList:participants})})
app.get('/api/rooms/:id/messages',auth,(req,res)=>{const room=db.prepare('SELECT id,status FROM rooms WHERE id=?').get(req.params.id);if(!room)return res.status(404).json({error:'Study room not found.'});const member=db.prepare('SELECT 1 FROM room_members WHERE room_id=? AND user_id=?').get(room.id,req.user.id);if(!member)return res.status(403).json({error:'Join this room before viewing chat.'});const messages=db.prepare(`SELECT m.id,m.room_id,m.user_id,u.name user_name,m.message,m.created_at FROM room_messages m JOIN users u ON u.id=m.user_id WHERE m.room_id=? ORDER BY m.id ASC LIMIT 200`).all(room.id);res.json({messages})})
app.post('/api/rooms/:id/messages',auth,(req,res)=>{const room=db.prepare('SELECT id,status FROM rooms WHERE id=?').get(req.params.id);if(!room)return res.status(404).json({error:'Study room not found.'});if(room.status==='Ended')return res.status(410).json({error:'This study room has ended.'});const member=db.prepare('SELECT 1 FROM room_members WHERE room_id=? AND user_id=?').get(room.id,req.user.id);if(!member)return res.status(403).json({error:'Join this room before chatting.'});const message=String(req.body.message||'').trim().slice(0,1000);if(!message)return res.status(400).json({error:'Message cannot be empty.'});const r=db.prepare('INSERT INTO room_messages(room_id,user_id,message) VALUES(?,?,?)').run(room.id,req.user.id,message);const saved=db.prepare(`SELECT m.id,m.room_id,m.user_id,u.name user_name,m.message,m.created_at FROM room_messages m JOIN users u ON u.id=m.user_id WHERE m.id=?`).get(r.lastInsertRowid);io.to(`room:${room.id}`).emit('room:message',saved);res.json({message:saved})})
app.post('/api/rooms/:id/leave',auth,(req,res)=>{const room=db.prepare('SELECT * FROM rooms WHERE id=?').get(req.params.id);if(!room)return res.status(404).json({error:'Study room not found.'});if(room.creator_id===req.user.id)return res.status(400).json({error:'Only leaving is available for members. The creator must end the room.'});db.prepare('DELETE FROM room_members WHERE room_id=? AND user_id=?').run(room.id,req.user.id);res.json({ok:true})})
app.delete('/api/rooms/:id',auth,(req,res)=>{const room=db.prepare('SELECT * FROM rooms WHERE id=?').get(req.params.id);if(!room)return res.status(404).json({error:'Study room not found.'});if(room.creator_id!==req.user.id)return res.status(403).json({error:'Only the room creator can end this room.'});const endedAt=new Date();const liveRows=db.prepare('SELECT * FROM study_live_sessions WHERE room_id=?').all(room.id);liveRows.forEach(l=>{const duration=Math.max(0,Math.floor((endedAt-new Date(l.started_at))/1000));if(duration>0)db.prepare('INSERT INTO study_sessions(user_id,date,start_time,end_time,duration,type) VALUES(?,?,?,?,?,?)').run(l.user_id,day(endedAt),l.started_at,endedAt.toISOString(),duration,'GROUP STUDY')});db.prepare('DELETE FROM study_live_sessions WHERE room_id=?').run(room.id);db.prepare('DELETE FROM room_messages WHERE room_id=?').run(room.id);db.prepare('DELETE FROM room_members WHERE room_id=?').run(room.id);db.prepare("UPDATE rooms SET status='Ended' WHERE id=?").run(room.id);io.to(`room:${room.id}`).emit('room:ended',{roomId:room.id});res.json({ok:true})})

io.on('connection',socket=>{socket.on('room:join',async({roomId,user})=>{const room=db.prepare('SELECT id,status FROM rooms WHERE id=?').get(Number(roomId));if(!room||room.status==='Ended')return;const member=db.prepare('SELECT 1 FROM room_members WHERE room_id=? AND user_id=?').get(room.id,Number(user?.id));if(!member)return;socket.join(`room:${room.id}`);socket.data.roomId=room.id;socket.data.userId=Number(user.id);socket.to(`room:${room.id}`).emit('room:user_joined',user)});socket.on('room:leave',({roomId,user})=>{const id=Number(roomId);if(socket.data.roomId===id){socket.leave(`room:${id}`);socket.to(`room:${id}`).emit('room:user_left',user);socket.data.roomId=null}})})

const dist=path.join(__dirname,'../client/dist');if(fs.existsSync(dist)){app.use(express.static(dist));app.get('/*splat',(req,res)=>res.sendFile(path.join(dist,'index.html')))}
server.listen(process.env.PORT||4000,()=>console.log('Diary API running on http://localhost:4000'))
